server {
    listen 8080; # Nginx listens on port 8080 (matching the Dockerfile EXPOSE)
    listen [::]:8080; # Listen on IPv6 as well

    server_name ui.lifejourney.online; # Or your domain name if serving publicly

    root /usr/share/nginx/html; # This is where your Angular build output will be copied

    index index.html index.htm; # Default files to serve

    location /.well-known/acme-challenge/ {
        try_files $uri =404;
        default_type "text/plain"; # Ensures correct content type
    }

    # Basic setup for all locations
    location / {
        try_files $uri $uri/ /index.html =404;
    }

    # Optional: Cache control for static assets (CSS, JS, images, fonts)
    # This helps with performance by instructing browsers to cache these files
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|woff|woff2|ttf|svg|eot)$ {
        expires 30d; # Cache for 30 days
        add_header Cache-Control "public, no-transform"; # Ensure public caching
    }

    # Optional: Gzip compression for faster loading
    # Enables compression for text-based files
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Deny access to hidden files (e.g., .git, .vscode)
    location ~ /\. {
        deny all;
    }
}